spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:27017/restaurant?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  rabbitmq:
    host: localhost
    port: 5672
    username: ulysses
    password: senha123
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /kitchen
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    beans:
      cache:
        time-to-live: 10s
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true