spring:
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:jdbc:postgresql://localhost:27017/restaurant?useSSL=false}
springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /payment
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    beans:
      cache:
        time-to-live: 10s
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true